### ISSUE TITLE
Superset admins cannot login if they are not staff on any course

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor-cairn#11]
A user who is an administrator on Superset but does not own any course in the Studio cannot login. This is normal behaviour for non-administrators, but not for administrators.

To reproduce:

    tutor local do createuser --superuser --staff admin admin@overhang.io
    tutor local do cairn-createuser --admin admin admin@overhang.io

Then, attempt to login to Superset.

**Comment by FahadKhalid210** [comment]
Hi @regisb, issue is not reproduced.

Steps:
1) Create user
```
tutor local do createuser --superuser --staff admin admin@overhang.io
tutor local do cairn-createuser --admin admin admin@overhang.io
```
2) Successfully login to Superset even user don't own any course.
<img width="1734" alt="image" src="https://github.com/overhangio/tutor-cairn/assets/79192414/541695f8-0cc2-4e27-9f41-1c66c712483d">


<img width="1251" alt="image" src="https://github.com/overhangio/tutor-cairn/assets/79192414/7f7c9f4c-0ec3-45b0-9bb9-47ea8f541119">

**Comment by regisb** [comment]
Awesome, let's close this :)
