### ISSUE TITLE
Superset's `AUTH_ROLES_SYNC_AT_LOGIN = True` makes it impossible to use role-based access controls

### ISSUE THREAD

**Issue by regisb** [overhangio/tutor-cairn#14]
Whenever an admin modifies the roles assigned to a user, the following warning pops up:

![Screenshot 2023-09-12 at 16-43-26 Superset](https://github.com/overhangio/tutor-cairn/assets/44319/7abf0506-cafe-47ae-aafe-5b4787bd98e6)

This means that it's basically not possible to customize the permissions associated to a user.

Instead, we could/should do the following:

- set `AUTH_ROLES_SYNC_AT_LOGIN = False` 
- keep the `_oauth_calculate_user_roles` method, which will be called only at user creation by `Base.SecurityManager.auth_user_oauth`.

**Comment by regisb** [comment]
Did you check that this new feature actually works, and that we don't need to change the `_oauth_calculate_user_roles` function?

**Comment by FahadKhalid210** [comment]
@regisb yes, it works without changing `_oauth_calculate_user_roles` function.
