### ISSUE TITLE
Missing arm64 support

### ISSUE THREAD

**Issue by audacioustux** [overhangio/tutor-cairn#24]
<img width="1025" alt="Screenshot 2023-12-30 at 6 55 07 PM" src="https://github.com/overhangio/tutor-cairn/assets/7238675/1ebb98df-2ce8-4235-94aa-bc907574fdb7">

Maybe this needs to be changed?
https://github.com/overhangio/tutor-cairn/blob/ce88178a2b03c3bb102e02c783d2daa06367a7c6/.gitlab-ci.yml#L7

Also, is there any particular reason of not using upstream container images?

**Comment by FahadKhalid210** [comment]
Hi @audacioustux 
Currently the images that are using in Cairn don't support ARM64 architecture.
For Reference:
[Superset Image](https://hub.docker.com/layers/apache/superset/3.0.1/images/sha256-e0b0dcdcbc2c62aae9e3882bb8f4ac50510efbe8369232639f73fbe6953b392d?context=explore)
[Clickhouse Image](https://hub.docker.com/layers/yandex/clickhouse-server/22.1.3.7/images/sha256-1cbf75aabe1e2cc9f62d1d9929c318a59ae552e2700e201db985b92a9bcabc6e?context=explore)
