### ISSUE TITLE
The request to sign in was denied - SSO Login

### ISSUE THREAD

**Issue by jjdeezy18** [overhangio/tutor-cairn#27]
Hi,

Just installed Cairn in Tutor version 17.0.0 but having issues during SSO login.
Upon checking the Applications under Django OAuth I don't have a created configuration for Cairn.

Not sure what I am missing, hope someone could assist.

Thank you!

**Comment by FahadKhalid210** [comment]
Hi @jjdeezy18 , Could you please tell us the steps that you follow?
Also add screenshot of issues you are facing during SSO.
Typically, the following steps are followed to enable Cairn:
- Install Plugin
- Enable the plugin
- Re-generate environment with `tutor config save`
- Restart platform

**Comment by jjdeezy18** [comment]
Hi @FahadKhalid210 , those were the steps that I did. Plugin is enabled for Cairn.

Please see screenshot below:

![SS](https://github.com/overhangio/tutor-cairn/assets/155486210/4a2d5894-6617-4967-8b3e-6647c69f3afa)

Also, I checked the Applications under Django OAuth I don't have a created configuration for Cairn (cairn-sso). 

So I am not sure if this is the configuration I am missing.

**Comment by regisb** [comment]
Did you run `tutor local launch`? (you should)

**Comment by jjdeezy18** [comment]
Hi @regisb,

Tried to redo the installation and managed to make it work. cairn-sso has been added also on Django OAuth Applications.
I think I messed up on the order of installing it.

Thank you so much for your help @FahadKhalid210 @regisb !

**Comment by jjdeezy18** [comment]
Hi again,

We installed another Tutor  version and we are having issues in SSO login of Cairn.
-- All settings are defined.
-- Done all the installation steps
-- All versions are updated

![image](https://github.com/overhangio/tutor-cairn/assets/155486210/dd8d0fb3-201c-442d-8abc-359972fdd929)

Thank you!

**Comment by FahadKhalid210** [comment]
@jjdeezy18 have you checked out [this](https://github.com/overhangio/tutor-cairn/issues/27#issuecomment-1888894852)?
Note: Only **staff** users have access to login on Superset

**Comment by jjdeezy18** [comment]
Hi @FahadKhalid210 ,

Yes, I just did the previous installation and set the user as Staff.

I even did this just to be sure:
tutor local do cairn-createuser --admin YOURUSERNAME YOURUSERNAME@YOUREMAIL.COM

**Comment by FahadKhalid210** [comment]
Hi @jjdeezy18 
make sure there is at least one course in your platform otherwise due to this [condition](https://github.com/overhangio/tutor-cairn/blob/97600a53507e6949e69f9d698c0d22d0c3d84654/tutorcairn/templates/cairn/build/cairn-superset/cairn/sso.py#L38), staff user will not be logged in to superset.

**Comment by FahadKhalid210** [comment]
Hi @jjdeezy18 
As mentioned earlier, please `restart the platform` after enabling the **plugin** and attempt to log in again. Additionally, could you kindly check the logs of both the LMS and Superset for any errors or anomalies encountered during the login process? If any errors are present, it would be immensely helpful if you could share them for further analysis.

**Comment by jjdeezy18** [comment]
Hi @FahadKhalid210 ,

Thank you for the support, it's working now.
