### ISSUE TITLE
Collecting SCORM statistics

### ISSUE THREAD

**Issue by T3-RnD** [overhangio/tutor-cairn#28]
I am wondering if the analytics app can record and store scorm data as it only tracks video watch time for now.

**Comment by regisb** [comment]
Please don't use Github issues for feature requests or for support. Instead, you should create a new topic in the official Open edX forum: https://discuss.openedx.org/

The process for troubleshooting an existing installation and for contributing to the platform is described in the docs:
https://docs.tutor.overhang.io/troubleshooting.html
https://docs.tutor.overhang.io/tutor.html#contributing
