### ISSUE TITLE
tutor-cairn codebase Python 3.12 upgrade

### ISSUE THREAD

**Issue by DawoudSheraz** [overhangio/tutor-cairn#31]
- [x] Ensure tutor-cairn codebase is compatible with Python 3.12
- [ ] Update Python to 3.12 in Dockerfile for nightly and ensure the image builds as expected. The changes would be merged to nightly  

See https://github.com/overhangio/tutor/issues/1004 for the context.

**Comment by FahadKhalid210** [comment]
@DawoudSheraz  CI checks are added. We won't attempt to install Python 3.12 in clickhouse image. We'll wait for the upstream upgrade to Ubuntu 24.04. 

For more details, click [here](https://github.com/overhangio/tutor-cairn/pull/34#discussion_r1540877146).


 
<img width="545" alt="image" src="https://github.com/overhangio/tutor-cairn/assets/79192414/fe10ef5d-bdad-4d0d-a7b6-17710aa7470a">

**Comment by DawoudSheraz** [comment]
Alright, thanks. Let's create a followup for Python upgrade and close this one out (because this is part of larger 3.12 upgrade initiative).

**Comment by FahadKhalid210** [comment]
https://github.com/overhangio/tutor-cairn/issues/37
