### ISSUE TITLE
Logs from mobile app is not tracked for analytics?

### ISSUE THREAD

**Issue by zameel7** [overhangio/tutor-cairn#41]
Are the logs from mobile app tracked in cairn? It doesn't seem so because we have had some analytics reports setup but we couldn't find any data of students who use the mobile app instead of the web app.

**Comment by zameel7** [comment]
@FahadKhalid210, any idea this is happening?

**Comment by Danyal-Faheem** [comment]
Hey @zameel7, sorry for the late reply. There was a maintainership change in progress.

Can you provide some further details on which specific logs are not being tracked? Do you mean the logs generated by the mobile apps themselves or the logs generated by the LMS and Studio for the events performed through the mobile app. The logs generated by the LMS and Studio should definitely be tracked for the actions that are performed on the mobile app. If these are not being tracked, we would need to look into this further.

**Comment by zameel7** [comment]
The tracking logs for video watch is not being captured when a mobile app
user watches a video component. This was one thing I noticed.

**Comment by Danyal-Faheem** [comment]
Thank you, we'll take a look into this matter.

Feel free to provide us with as much information as you can.

**Comment by zameel7** [comment]
Thank you! I got engaged to some other work rn, will update if I get any more details.

**Comment by Danyal-Faheem** [comment]
Hi @zameel7, I was testing this out and I noticed that the mobile app uses a different video player than the website. The video player on the mobile app does not throw tracking logs which are the ones that cairn uses for generating analytical reports. However, I can see that analytics for other events such as course enrollments, block completions, platform time spent etc are being tracked by cairn as they throw tracking logs.

**Comment by zameel7** [comment]
Hey @Danyal-Faheem! Thats a good find. Is that same in the new mobile app too? If so, creating an analytics graph based on the tracking logs if most users use mobile would be useless right

**Comment by Danyal-Faheem** [comment]
I tested this using tutor v18.1.4 and [tutor-android v18.0.0](https://github.com/overhangio/tutor-android/releases/tag/v18.0.0) which uses the new [openedx-app-android](https://github.com/openedx/openedx-app-android). 

> If so, creating an analytics graph based on the tracking logs if most users use mobile would be useless right

That depends on what kind of analytics you are looking for. If you just want video analytics, then yes. However, tracking logs are generated for a lot of other events that might be very useful such as course enrollments, block completion, grading.

**Comment by zameel7** [comment]
Yep, other events are great.

**Comment by Danyal-Faheem** [comment]
Right, I am going to close this issue then as it is not related to cairn but moreso related to how the openedx android app generates logs.
